using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace WPFApp
{

    public partial class MainWindow : Window
    {
        // DB for Products
        private ProductDB _productDB;
        public MainWindow()
        {
            InitializeComponent();
            _productDB = new ProductDB();
        }

        // Calls function upon window load
        private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            LoadProducts();
        }

        // Function that adds a new product to the DB
        private void AddProduct(object sender, RoutedEventArgs e)
        {
            int item_id = 0; // Generated by DB
            string name = NameTextBox.Text;
            int quantity = int.Parse(QuantityTextBox.Text);
            decimal price = decimal.Parse(PriceTextBox.Text);
            string description = DescriptionTextBox.Text;

            // Creates a new product using inputted data
            Product newProduct = new Product
            {
                Item_ID = item_id,
                Name = name,
                Quantity = quantity,
                Price = price,
                Description = description,
            };

            _productDB.InsertProduct(newProduct);
            LoadProducts();

            // Clear Input Fields upon adding product
            NameTextBox.Clear();
            QuantityTextBox.Clear();
            PriceTextBox.Clear();
            DescriptionTextBox.Clear();
        }

        // Helper Function: Loads products into window data grid
        private void LoadProducts()
        {
            var products = _productDB.GetProduct();
            dataGrid1.ItemsSource = products;
        }
    }
}